name: Java Maven deploy 

on: 
  workflow_call:
    inputs:
      shouldMaven:
        required: false
        type: string
      javaVersion:
        required: true
        type: string
      pathPom:
        required: true
        type: string
jobs:
  build:
    name: Deploy maven test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ inputs.javaVersion }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify --file ${{ inputs.pathPom }}
      - name: Create Maven Package
        run: mvn package --file ${{ inputs.pathPom }}
      - name: Moving target into root path 
        run: mv --force --verbose ${{ inputs.pathPom }}/target ./
      - name: See path where we are 
        run: pwd && ls -l
      - name: Deploy java
        run: java -jar target/java-project-1.0-SNAPSHOT.jar Diego
